parameters:
#    krucsoati_test.example.class: krucsoati\TestBundle\Example

services:
#    krucsoati_test.example:
#        class: %krucsoati_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
